# Generated by Django 4.0.2 on 2022-02-18 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('color', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='symbols/')),
                ('description', models.CharField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Wonder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='wonders/')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.expansion')),
            ],
        ),
        migrations.CreateModel(
            name='WonderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.symbol')),
                ('wonder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.wonder')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.expansion')),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.symbol')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guide.cardtype')),
            ],
        ),
    ]
