# Generated by Django 4.0.2 on 2023-02-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guide', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['name', 'origin']},
        ),
        migrations.AlterModelOptions(
            name='cardtype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='expansion',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='symbol',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='wonder',
            options={'ordering': ['name', 'origin']},
        ),
        migrations.AlterModelOptions(
            name='wonderstep',
            options={'ordering': ['wonder', 'level']},
        ),
    ]
